# Generated by Django 5.2.5 on 2025-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_offer_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('education', models.TextField(help_text='List degrees, certifications, or qualifications')),
                ('expertise', models.TextField(help_text='Describe skills, technologies, and areas of expertise')),
            ],
        ),
    ]
